# development:
#   cloud_name: "dgfkp3dzm"
#   api_key: "716711838362953"
#   api_secret: "ljFwL9mm-Pk0AivIbpz90e3XVJs"
#   secure: true

# production:
#   cloud_name: "dgfkp3dzm"
#   api_key: "716711838362953"
#   api_secret: "ljFwL9mm-Pk0AivIbpz90e3XVJs"
#   secure: true
